### ISSUE TITLE
chrome on android "feels" currently worse than earlier versions 

### ISSUE THREAD

**Issue by ukscone** [dicekeys/beta-program#25]
[all this is anecdotal as my dice are now locked into the case so my "perm" key so no photos or videos atm]

 the updates to staging that made the image updates in the camera view be faster & for firefox & safari seem to have made use on chrome a lot worse for the actual reading of the dice. it seems to take ages for actual recognise the dice and display the generated image. get the image with the red/green overlay a lot more often but hardly ever get a dice image. it also seems to be a lot more light sensitive. less well lit areas and areas with light coming from the side that used to be ok are now not really that great. it also seems to work better although for low values of better landscape rather than portrait and the generated image seems to be as the box is orientated rather than rotated to be consistant

i'm using an LG Aristo 3 phone with android 9 and chrome version 85.0.4183.101

**Comment by UppaJung** [comment]
@ukscone 

Some of this might be perception, as it's now easier to see the lag between when video arrives and when we augment it with information about the dice)

Another part may be real, as we're may be scanning the images at a different resolution now that is slower.

If you haven't locked in your dice or are not using them for anything private until your production DiceKeys arrive, please attach a screen shot of the scanning process with those dice.

If you don't want to scan in those dice because you are relying on them to be private, please attach a photo of the scanning interface with no dice present.  (Or, if you have a second device, render a random DiceKey on the screen with the app on another device and then get a picture of scanning that.)

**Comment by ukscone** [comment]
i'm actually not going to be doing anything serious with them as it's the beta so i'll take some photos & if possible video in the morning (my time) as currently on hour 3 of a kernel build so everything is tied up atm

**Comment by ukscone** [comment]
sorry RL interfered so haven't got around to doing more pictures/videos yet also not able to get scrcpy working on my chromebook yet so need to try to "repair" a laptop to be able to do a video. will try to get to it this weekend

**Comment by ukscone** [comment]
sorry i've been under the weather the last week or so and didn't get around to doing any testing again until last night however it was a lot better on android chrome on my phone & with silk on kindle fire 8"

less than a minute most times in reasonably poor lighting on my bedside desk.
