### ISSUE TITLE
ridges on the locking part

### ISSUE THREAD

**Issue by ukscone** [dicekeys/beta-program#37]
While messing around with the dice locked in position i've notice that the ridges of the locking part of the base cast very strong shadows on the dice with directional light (desk by a window, lamp on desk,...) which probably effects ease/speed of recognition. Do they really need to be so high for structural strength? maybe lower them a mm or two so they are a little more flush with the dice face

**Comment by p0lt** [comment]
same as #14

**Comment by UppaJung** [comment]
They are 1.5mm thick and they are what keep the dice from falling out, so we can't significantly reduce the height.  If we could have our dream tolerances for dice manufacturing we might be able to hold the dice in place by having the plastic wrap around only the curved parts, but there's no dice producer that can currently promise that level of precision.

If we were using 16mm dice instead of 12mm, the relative effect would be smaller, but, we'd be using 64/27 as much plastic for the dice.

**Comment by UppaJung** [comment]
Unless we have a good way to fix this in hardware, we'll be continuing to try to make the software more resilient to shadows.
